# Generated by Django 4.0 on 2021-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
